### ISSUE TITLE
worker repeatedly crashing (?) / respwaning

### ISSUE THREAD

**Issue by KrishnaPG** [SocketCluster/sc-sample-inventory#3]
Fresh installation. After logging in (with default populated 'bob' username and password), whenever we go into the any of the listed categories, the console is populated with so  many errors (Screenshot below), as well the server is dumping below errors

```
1469169722225 - Origin: Worker (PID 9544)
   [Error] TypeError: Cannot read property 'category' of null
    at crudOptions.schema.Product.views.categoryView.transform (e:\Codebase\sc-sample-inventory\worker.js:65:78)
    at module.exports.constructTransformedRethinkQuery (e:\Codebase\sc-sample-inventory\node_modules\sc-crud-rethink\query-transformer.js:24:20)
    at SCCRUDRethink.read (e:\Codebase\sc-sample-inventory\node_modules\sc-crud-rethink\index.js:308:26)
    at Emitter.<anonymous> (e:\Codebase\sc-sample-inventory\node_modules\sc-crud-rethink\index.js:641:10)
    at Emitter.emit (e:\Codebase\sc-sample-inventory\node_modules\component-emitter\index.js:131:20)
    at Emitter.SCEmitter.emit (e:\Codebase\sc-sample-inventory\node_modules\sc-emitter\index.js:28:26)
    at e:\Codebase\sc-sample-inventory\node_modules\socketcluster-server\scsocket.js:113:44
    at e:\Codebase\sc-sample-inventory\node_modules\socketcluster-server\scserver.js:666:11
    at e:\Codebase\sc-sample-inventory\node_modules\socketcluster-server\node_modules\async\lib\async.js:52:16
    at e:\Codebase\sc-sample-inventory\node_modules\socketcluster-server\node_modules\async\lib\async.js:269:32
    at e:\Codebase\sc-sample-inventory\node_modules\socketcluster-server\node_modules\async\lib\async.js:44:16
    at e:\Codebase\sc-sample-inventory\node_modules\sc-crud-rethink\filter.js:49:13
    at mustBeLoggedIn (e:\Codebase\sc-sample-inventory\worker.js:93:7)
    at Object.<anonymous> (e:\Codebase\sc-sample-inventory\node_modules\sc-crud-rethink\filter.js:40:9)
    at e:\Codebase\sc-sample-inventory\node_modules\socketcluster-server\node_modules\async\lib\async.js:1165:24
    at iterate (e:\Codebase\sc-sample-inventory\node_modules\socketcluster-server\node_modules\async\lib\async.js:262:13)
1469169722290 - Worker 0 exited - Exit code: 1
   >> Worker PID: 13260
Creating a pool connected to 192.168.99.100:28015
1469169722936 - Worker 0 was respawned
```

![image](https://cloud.githubusercontent.com/assets/4610831/17048816/77607330-5006-11e6-9867-429cf4f8444d.png)

**Comment by jondubois** [comment]
I cannot reproduce - This issue is likely to have been fixed since then. If not, feel free to re-open this.
